In [64]:
#importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
df=pd.read_excel("Bank_Personal_Loan_Modelling.xlsx",na_values=['.',':','?','!','@','#','$','%','^','&','*',','])

In [66]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ID                  5000 non-null   int64  
 1   Age                 5000 non-null   int64  
 2   Experience          5000 non-null   int64  
 3   Income              5000 non-null   int64  
 4   ZIP Code            5000 non-null   int64  
 5   Family              5000 non-null   int64  
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64  
 8   Mortgage            5000 non-null   int64  
 9   Personal Loan       5000 non-null   int64  
 10  Securities Account  5000 non-null   int64  
 11  CD Account          5000 non-null   int64  
 12  Online              5000 non-null   int64  
 13  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [68]:
df.nunique()

ID                    5000
Age                     45
Experience              47
Income                 162
ZIP Code               467
Family                   4
CCAvg                  108
Education                3
Mortgage               347
Personal Loan            2
Securities Account       2
CD Account               2
Online                   2
CreditCard               2
dtype: int64

In [69]:
df = df.drop(["ID","ZIP Code",], axis=1)

In [70]:
df.isnull().sum()

Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [71]:
df.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

In [72]:
df.dtypes

Age                     int64
Experience              int64
Income                  int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Personal Loan           int64
Securities Account      int64
CD Account              int64
Online                  int64
CreditCard              int64
dtype: object

In [73]:
for col in ['Education','Securities Account','CD Account','Online','Personal Loan','Family','CreditCard']:
  df[col] = df[col].astype('category')

In [74]:
df.dtypes

Age                      int64
Experience               int64
Income                   int64
Family                category
CCAvg                  float64
Education             category
Mortgage                 int64
Personal Loan         category
Securities Account    category
CD Account            category
Online                category
CreditCard            category
dtype: object

In [75]:
cat_cols=['Family','Education','Personal Loan','Securities Account','CD Account','Online']

In [76]:
num_cols=['Age','Income', 'Experience', 'CCAvg', 'Mortgage']

In [77]:
df[num_cols].describe()

Age       Income   Experience        CCAvg     Mortgage
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000
mean     45.338400    73.774200    20.104600     1.937938    56.498800
std      11.463166    46.033729    11.467954     1.747659   101.713802
min      23.000000     8.000000    -3.000000     0.000000     0.000000
25%      35.000000    39.000000    10.000000     0.700000     0.000000
50%      45.000000    64.000000    20.000000     1.500000     0.000000
75%      55.000000    98.000000    30.000000     2.500000   101.000000
max      67.000000   224.000000    43.000000    10.000000   635.000000

In [78]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [79]:
X = df.drop('CreditCard',axis=1)
y= df['CreditCard']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=125, stratify=y)

In [81]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 11)
(1000, 11)
(4000,)
(1000,)


In [82]:
df.value_counts(['CreditCard'])/5000

CreditCard
0             0.706
1             0.294
dtype: float64

In [83]:
y_train.value_counts(normalize=True)

0    0.706
1    0.294
Name: CreditCard, dtype: float64

In [84]:
y_test.value_counts(normalize=True)

0    0.706
1    0.294
Name: CreditCard, dtype: float64

In [85]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler = scaler.fit(X_train[num_cols])
X_train_num_std = pd.DataFrame(scaler.transform(X_train[num_cols]), columns=X_train[num_cols].columns)
X_test_num_std = pd.DataFrame(scaler.transform(X_test[num_cols]), columns=X_test[num_cols].columns)

In [86]:
X_train_num_std.isnull().sum()

Age           0
Income        0
Experience    0
CCAvg         0
Mortgage      0
dtype: int64

In [87]:
X_test_num_std.isnull().sum()

Age           0
Income        0
Experience    0
CCAvg         0
Mortgage      0
dtype: int64

In [88]:
X_train_cat_dum = pd.get_dummies((X_train[cat_cols]),drop_first=True)
X_test_cat_dum = pd.get_dummies((X_test[cat_cols]),drop_first=True)

In [89]:
X_train_cat_dum

Family_2  Family_3  Family_4  Education_2  Education_3  Personal Loan_1  \
3877         0         0         0            0            0                0   
2103         1         0         0            0            0                0   
3131         0         1         0            1            0                0   
1903         0         1         0            0            1                0   
1133         0         0         0            1            0                0   
...        ...       ...       ...          ...          ...              ...   
242          0         0         0            0            1                0   
3507         0         0         0            1            0                0   
1475         1         0         0            0            1                0   
3808         1         0         0            0            0                0   
755          0         0         1            1            0                0   

      Securities Account_1  CD Account_1  Online_1  
3877                     0             0         0  
2103                     0             0         1  
3131                     0             0         1  
1903                     0             0         0  
1133                     0             0         0  
...                    ...           ...       ...  
242                      0             0         0  
3507                     0             1         1  
1475                     0             0         0  
3808                     0             0         0  
755                      0             0         0  

[4000 rows x 9 columns]

In [90]:
X_test_cat_dum

Family_2  Family_3  Family_4  Education_2  Education_3  Personal Loan_1  \
3777         0         0         0            0            0                0   
3422         0         0         0            0            1                0   
4072         0         0         0            0            1                0   
2375         0         0         1            0            1                0   
3482         0         0         0            0            0                0   
...        ...       ...       ...          ...          ...              ...   
1483         0         0         0            0            0                0   
4750         0         0         0            0            1                0   
1098         0         0         0            0            0                0   
3084         0         1         0            1            0                1   
1403         0         0         1            0            0                0   

      Securities Account_1  CD Account_1  Online_1  
3777                     0             0         1  
3422                     0             0         0  
4072                     0             0         1  
2375                     1             1         1  
3482                     1             0         0  
...                    ...           ...       ...  
1483                     1             0         1  
4750                     0             0         0  
1098                     0             0         1  
3084                     0             0         0  
1403                     1             0         0  

[1000 rows x 9 columns]

In [91]:
X_train_num_std = X_train_num_std.reset_index()
X_train_num_std

index       Age    Income  Experience     CCAvg  Mortgage
0         0 -1.426470 -0.709473   -1.405600 -0.537999 -0.553034
1         1 -0.730641  1.753823   -0.622427  2.623346 -0.553034
2         2  0.139144 -0.269599    0.160746  0.439144  1.125968
3         3  0.921951 -0.511530    0.508823 -0.308083 -0.553034
4         4 -1.252513 -0.995392   -1.405600  0.036791 -0.553034
...     ...       ...       ...         ...       ...       ...
3995   3995 -0.382727  0.038313   -0.361369  1.013934  2.245303
3996   3996  0.400080  0.214263    0.247766  0.421900 -0.553034
3997   3997 -0.121792  0.104294   -0.100311  1.071413  2.125374
3998   3998 -0.991577  1.731829   -0.883485  2.623346 -0.553034
3999   3999  0.921951 -0.621499    0.856900 -0.710436 -0.553034

[4000 rows x 6 columns]

In [92]:
X_train_num_std = X_train_num_std.drop(["index"], axis=1)

In [93]:
X_train_num_std

Age    Income  Experience     CCAvg  Mortgage
0    -1.426470 -0.709473   -1.405600 -0.537999 -0.553034
1    -0.730641  1.753823   -0.622427  2.623346 -0.553034
2     0.139144 -0.269599    0.160746  0.439144  1.125968
3     0.921951 -0.511530    0.508823 -0.308083 -0.553034
4    -1.252513 -0.995392   -1.405600  0.036791 -0.553034
...        ...       ...         ...       ...       ...
3995 -0.382727  0.038313   -0.361369  1.013934  2.245303
3996  0.400080  0.214263    0.247766  0.421900 -0.553034
3997 -0.121792  0.104294   -0.100311  1.071413  2.125374
3998 -0.991577  1.731829   -0.883485  2.623346 -0.553034
3999  0.921951 -0.621499    0.856900 -0.710436 -0.553034

[4000 rows x 5 columns]

In [94]:
X_train_cat_dum = X_train_cat_dum.reset_index()
X_train_cat_dum

index  Family_2  Family_3  Family_4  Education_2  Education_3  \
0      3877         0         0         0            0            0   
1      2103         1         0         0            0            0   
2      3131         0         1         0            1            0   
3      1903         0         1         0            0            1   
4      1133         0         0         0            1            0   
...     ...       ...       ...       ...          ...          ...   
3995    242         0         0         0            0            1   
3996   3507         0         0         0            1            0   
3997   1475         1         0         0            0            1   
3998   3808         1         0         0            0            0   
3999    755         0         0         1            1            0   

      Personal Loan_1  Securities Account_1  CD Account_1  Online_1  
0                   0                     0             0         0  
1                   0                     0             0         1  
2                   0                     0             0         1  
3                   0                     0             0         0  
4                   0                     0             0         0  
...               ...                   ...           ...       ...  
3995                0                     0             0         0  
3996                0                     0             1         1  
3997                0                     0             0         0  
3998                0                     0             0         0  
3999                0                     0             0         0  

[4000 rows x 10 columns]

In [95]:
X_train_cat_dum = X_train_cat_dum.drop(["index"], axis=1)

In [96]:
X_train_cat_dum

Family_2  Family_3  Family_4  Education_2  Education_3  Personal Loan_1  \
0            0         0         0            0            0                0   
1            1         0         0            0            0                0   
2            0         1         0            1            0                0   
3            0         1         0            0            1                0   
4            0         0         0            1            0                0   
...        ...       ...       ...          ...          ...              ...   
3995         0         0         0            0            1                0   
3996         0         0         0            1            0                0   
3997         1         0         0            0            1                0   
3998         1         0         0            0            0                0   
3999         0         0         1            1            0                0   

      Securities Account_1  CD Account_1  Online_1  
0                        0             0         0  
1                        0             0         1  
2                        0             0         1  
3                        0             0         0  
4                        0             0         0  
...                    ...           ...       ...  
3995                     0             0         0  
3996                     0             1         1  
3997                     0             0         0  
3998                     0             0         0  
3999                     0             0         0  

[4000 rows x 9 columns]

In [97]:
X_test_num_std = X_test_num_std.reset_index()
X_test_num_std

index       Age    Income  Experience     CCAvg  Mortgage
0        0  1.443822  0.544169    1.466035 -0.595478  0.956069
1        1  0.226122 -0.709473    0.247766 -0.308083 -0.553034
2        2 -0.295749  0.104294   -0.274350 -0.537999 -0.553034
3        3  0.834972 -0.093649    0.856900 -0.365562 -0.553034
4        4  1.008929  0.390213    1.117958  1.358808  0.256485
..     ...       ...       ...         ...       ...       ...
995    995  1.095908 -0.225612    1.030939 -0.193125 -0.553034
996    996  1.791736 -0.775455    1.814112 -0.480520 -0.553034
997    997  0.052165  0.896068   -0.013292 -1.112789 -0.553034
998    998 -1.687405  1.225974   -1.753677 -0.710436 -0.553034
999    999 -1.165534 -0.489536   -1.231562 -0.997831  0.986052

[1000 rows x 6 columns]

In [98]:
X_test_num_std = X_test_num_std.drop(["index"], axis=1)

In [99]:
X_test_num_std

Age    Income  Experience     CCAvg  Mortgage
0    1.443822  0.544169    1.466035 -0.595478  0.956069
1    0.226122 -0.709473    0.247766 -0.308083 -0.553034
2   -0.295749  0.104294   -0.274350 -0.537999 -0.553034
3    0.834972 -0.093649    0.856900 -0.365562 -0.553034
4    1.008929  0.390213    1.117958  1.358808  0.256485
..        ...       ...         ...       ...       ...
995  1.095908 -0.225612    1.030939 -0.193125 -0.553034
996  1.791736 -0.775455    1.814112 -0.480520 -0.553034
997  0.052165  0.896068   -0.013292 -1.112789 -0.553034
998 -1.687405  1.225974   -1.753677 -0.710436 -0.553034
999 -1.165534 -0.489536   -1.231562 -0.997831  0.986052

[1000 rows x 5 columns]

In [100]:
X_test_cat_dum = X_test_cat_dum.reset_index()
X_test_cat_dum

index  Family_2  Family_3  Family_4  Education_2  Education_3  \
0     3777         0         0         0            0            0   
1     3422         0         0         0            0            1   
2     4072         0         0         0            0            1   
3     2375         0         0         1            0            1   
4     3482         0         0         0            0            0   
..     ...       ...       ...       ...          ...          ...   
995   1483         0         0         0            0            0   
996   4750         0         0         0            0            1   
997   1098         0         0         0            0            0   
998   3084         0         1         0            1            0   
999   1403         0         0         1            0            0   

     Personal Loan_1  Securities Account_1  CD Account_1  Online_1  
0                  0                     0             0         1  
1                  0                     0             0         0  
2                  0                     0             0         1  
3                  0                     1             1         1  
4                  0                     1             0         0  
..               ...                   ...           ...       ...  
995                0                     1             0         1  
996                0                     0             0         0  
997                0                     0             0         1  
998                1                     0             0         0  
999                0                     1             0         0  

[1000 rows x 10 columns]

In [101]:
X_test_cat_dum = X_test_cat_dum.drop(["index"], axis=1)

In [102]:
X_test_cat_dum

Family_2  Family_3  Family_4  Education_2  Education_3  Personal Loan_1  \
0           0         0         0            0            0                0   
1           0         0         0            0            1                0   
2           0         0         0            0            1                0   
3           0         0         1            0            1                0   
4           0         0         0            0            0                0   
..        ...       ...       ...          ...          ...              ...   
995         0         0         0            0            0                0   
996         0         0         0            0            1                0   
997         0         0         0            0            0                0   
998         0         1         0            1            0                1   
999         0         0         1            0            0                0   

     Securities Account_1  CD Account_1  Online_1  
0                       0             0         1  
1                       0             0         0  
2                       0             0         1  
3                       1             1         1  
4                       1             0         0  
..                    ...           ...       ...  
995                     1             0         1  
996                     0             0         0  
997                     0             0         1  
998                     0             0         0  
999                     1             0         0  

[1000 rows x 9 columns]

In [103]:
final_X_train = pd.concat([X_train_num_std, X_train_cat_dum], axis=1)

In [104]:
final_X_test = pd.concat([X_test_num_std, X_test_cat_dum], axis=1)

In [105]:
final_X_train.isnull().sum()

Age                     0
Income                  0
Experience              0
CCAvg                   0
Mortgage                0
Family_2                0
Family_3                0
Family_4                0
Education_2             0
Education_3             0
Personal Loan_1         0
Securities Account_1    0
CD Account_1            0
Online_1                0
dtype: int64

In [106]:
final_X_test.isnull().sum()

Age                     0
Income                  0
Experience              0
CCAvg                   0
Mortgage                0
Family_2                0
Family_3                0
Family_4                0
Education_2             0
Education_3             0
Personal Loan_1         0
Securities Account_1    0
CD Account_1            0
Online_1                0
dtype: int64

In [107]:
final_X_train

Age    Income  Experience     CCAvg  Mortgage  Family_2  Family_3  \
0    -1.426470 -0.709473   -1.405600 -0.537999 -0.553034         0         0   
1    -0.730641  1.753823   -0.622427  2.623346 -0.553034         1         0   
2     0.139144 -0.269599    0.160746  0.439144  1.125968         0         1   
3     0.921951 -0.511530    0.508823 -0.308083 -0.553034         0         1   
4    -1.252513 -0.995392   -1.405600  0.036791 -0.553034         0         0   
...        ...       ...         ...       ...       ...       ...       ...   
3995 -0.382727  0.038313   -0.361369  1.013934  2.245303         0         0   
3996  0.400080  0.214263    0.247766  0.421900 -0.553034         0         0   
3997 -0.121792  0.104294   -0.100311  1.071413  2.125374         1         0   
3998 -0.991577  1.731829   -0.883485  2.623346 -0.553034         1         0   
3999  0.921951 -0.621499    0.856900 -0.710436 -0.553034         0         0   

      Family_4  Education_2  Education_3  Personal Loan_1  \
0            0            0            0                0   
1            0            0            0                0   
2            0            1            0                0   
3            0            0            1                0   
4            0            1            0                0   
...        ...          ...          ...              ...   
3995         0            0            1                0   
3996         0            1            0                0   
3997         0            0            1                0   
3998         0            0            0                0   
3999         1            1            0                0   

      Securities Account_1  CD Account_1  Online_1  
0                        0             0         0  
1                        0             0         1  
2                        0             0         1  
3                        0             0         0  
4                        0             0         0  
...                    ...           ...       ...  
3995                     0             0         0  
3996                     0             1         1  
3997                     0             0         0  
3998                     0             0         0  
3999                     0             0         0  

[4000 rows x 14 columns]

In [108]:
final_X_test

Age    Income  Experience     CCAvg  Mortgage  Family_2  Family_3  \
0    1.443822  0.544169    1.466035 -0.595478  0.956069         0         0   
1    0.226122 -0.709473    0.247766 -0.308083 -0.553034         0         0   
2   -0.295749  0.104294   -0.274350 -0.537999 -0.553034         0         0   
3    0.834972 -0.093649    0.856900 -0.365562 -0.553034         0         0   
4    1.008929  0.390213    1.117958  1.358808  0.256485         0         0   
..        ...       ...         ...       ...       ...       ...       ...   
995  1.095908 -0.225612    1.030939 -0.193125 -0.553034         0         0   
996  1.791736 -0.775455    1.814112 -0.480520 -0.553034         0         0   
997  0.052165  0.896068   -0.013292 -1.112789 -0.553034         0         0   
998 -1.687405  1.225974   -1.753677 -0.710436 -0.553034         0         1   
999 -1.165534 -0.489536   -1.231562 -0.997831  0.986052         0         0   

     Family_4  Education_2  Education_3  Personal Loan_1  \
0           0            0            0                0   
1           0            0            1                0   
2           0            0            1                0   
3           1            0            1                0   
4           0            0            0                0   
..        ...          ...          ...              ...   
995         0            0            0                0   
996         0            0            1                0   
997         0            0            0                0   
998         0            1            0                1   
999         1            0            0                0   

     Securities Account_1  CD Account_1  Online_1  
0                       0             0         1  
1                       0             0         0  
2                       0             0         1  
3                       1             1         1  
4                       1             0         0  
..                    ...           ...       ...  
995                     1             0         1  
996                     0             0         0  
997                     0             0         1  
998                     0             0         0  
999                     1             0         0  

[1000 rows x 14 columns]

In [109]:
from sklearn.linear_model import LogisticRegression

In [110]:
lr = LogisticRegression()
lr = lr.fit(final_X_train,y_train)

In [111]:
y_train_preds = lr.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
y_test_preds = lr.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [113]:
from sklearn.metrics import confusion_matrix
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[2776,   48],
       [ 979,  197]])

In [114]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[696,  10],
       [252,  42]])

In [115]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

0.74325

In [116]:
accuracy_score(y_test,y_test_preds)

0.738

In [117]:
from sklearn.ensemble import RandomForestClassifier

In [118]:
rfc = RandomForestClassifier()
rfc = rfc.fit(final_X_train, y_train)

In [119]:
y_train_preds = rfc.predict(final_X_train)
y_train_preds[0:10]

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [120]:
y_test_preds = rfc.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [121]:
from sklearn.metrics import confusion_matrix
confusionma2trix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[696,  10],
       [252,  42]])

In [122]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[638,  68],
       [231,  63]])

In [123]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

0.997

In [124]:
accuracy_score(y_test,y_test_preds)

0.701

In [125]:
import pickle


In [126]:
print('saving model as pkl file.......')
pickle.dump(lr, open('lr.pkl','wb'))

saving model as pkl file.......
